"""owned voice rooms, live speech and cited insights

Revision ID: 0004_live_rooms
Revises: 0004_meeting_boards
"""

import sqlalchemy as sa
from alembic import op

revision = "0004_live_rooms"
down_revision = "0004_meeting_boards"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "live_rooms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("language", sa.String(length=4), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("invite_nonce", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("meeting_id", sa.Uuid(), nullable=True),
        sa.Column("analysis_status", sa.String(length=24), nullable=False),
        sa.Column("analysis_error", sa.String(length=48), nullable=True),
        sa.Column("analysis_through", sa.Integer(), nullable=False),
        sa.Column("analysis_lease", sa.Uuid(), nullable=True),
        sa.Column("analysis_lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("analysis_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("transcript_revision", sa.Integer(), nullable=False),
        sa.Column("audio_error", sa.String(length=48), nullable=True),
        sa.Column("insights", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'ending', 'ended')", name=op.f("ck_live_rooms_status")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_live_rooms_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_live_rooms_meeting_id_meetings"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_live_rooms_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_live_rooms")),
    )
    op.create_index(
        op.f("ix_live_rooms_workspace_id"), "live_rooms", ["workspace_id"], unique=False
    )
    op.create_table(
        "live_participants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("is_host", sa.Boolean(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("stream_token", sa.Uuid(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["live_rooms.id"],
            name=op.f("fk_live_participants_room_id_live_rooms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_live_participants_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_live_participants")),
    )
    op.create_index(
        op.f("ix_live_participants_room_id"), "live_participants", ["room_id"], unique=False
    )
    op.create_table(
        "live_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("participant_id", sa.Uuid(), nullable=False),
        sa.Column("start", sa.Float(), nullable=False),
        sa.Column("end", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("lease", sa.Uuid(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=48), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'done', 'failed')", name=op.f("ck_live_chunks_status")
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["live_participants.id"],
            name=op.f("fk_live_chunks_participant_id_live_participants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["live_rooms.id"],
            name=op.f("fk_live_chunks_room_id_live_rooms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_live_chunks")),
    )
    op.create_index(
        "ix_live_chunks_claim", "live_chunks", ["status", "lease_until", "created_at"], unique=False
    )
    op.create_index("ix_live_chunks_room_start", "live_chunks", ["room_id", "start"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_live_chunks_room_start", table_name="live_chunks")
    op.drop_index("ix_live_chunks_claim", table_name="live_chunks")
    op.drop_table("live_chunks")
    op.drop_index(op.f("ix_live_participants_room_id"), table_name="live_participants")
    op.drop_table("live_participants")
    op.drop_index(op.f("ix_live_rooms_workspace_id"), table_name="live_rooms")
    op.drop_table("live_rooms")
    # ### end Alembic commands ###
